plugins {
    id 'java-library'
    id 'io.spring.dependency-management'
}

dependencyManagement {
    imports {
        mavenBom 'org.springframework.boot:spring-boot-dependencies:4.1.0'
    }
}

dependencies {
    api project(':eventdock-core')
    api project(':eventdock-outbox')
    api project(':eventdock-inbox')
    implementation project(':eventdock-storage-postgresql')
    implementation project(':eventdock-transport-kafka')
    implementation 'org.springframework.boot:spring-boot-autoconfigure'
    implementation 'org.springframework.boot:spring-boot-kafka'
    implementation 'org.springframework:spring-jdbc'
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'tools.jackson.core:jackson-databind'
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
