plugins {
    id 'java-library'
}

dependencies {
    api project(':eventdock-outbox')
    api project(':eventdock-inbox')
    runtimeOnly 'org.postgresql:postgresql:42.7.8'
    testImplementation platform('org.junit:junit-bom:6.0.3')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation platform('org.testcontainers:testcontainers-bom:2.0.5')
    testImplementation 'org.testcontainers:testcontainers-postgresql'
    testImplementation 'org.testcontainers:testcontainers-junit-jupiter'
    testImplementation 'org.postgresql:postgresql:42.7.8'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
